--
-- CopyData Module supporting tables
--
-- @original author Alexander Shereshevsky - Amdocs (shereshevsky@gmail.com)
-- @created Mar 16,2013
-- @last_modification Mar 16,2013
--

CREATE TABLE COPYDATA_PROJECTS
(
  PROJECT         VARCHAR2(30 BYTE),
  SRC_OWNER       VARCHAR2(30 BYTE),
  SRC_DB          VARCHAR2(30 BYTE),
  TRG_OWNER       VARCHAR2(30 BYTE),
  TRG_DB          VARCHAR2(30 BYTE),
  TRG_TABLE_NAME  VARCHAR2(30 BYTE),
  WHERE_ST        VARCHAR2(200 BYTE),
  TRUNCATE_TABLE  NUMBER(1),
  MISSING         NUMBER(1),
  CRE_BACKUP      NUMBER(1),
  PROJECT_OWNER   VARCHAR2(30 BYTE),
  SNAPSHOT        NUMBER(1),
  HASH            VARCHAR2(30 BYTE),
  SEQUENCE        NUMBER(1),
  RESTORE         NUMBER(1),
  SRC_TABLE_NAME  VARCHAR2(30 BYTE)
);


CREATE UNIQUE INDEX COPYDATA_PROJECTS_PK ON OWEB.COPYDATA_PROJECTS
(PROJECT, PROJECT_OWNER, SRC_OWNER, SRC_DB, TRG_OWNER, 
TRG_DB, TRG_TABLE_NAME);


ALTER TABLE COPYDATA_PROJECTS ADD (
  CONSTRAINT COPYDATA_PROJECTS_PK
  PRIMARY KEY
  (PROJECT, PROJECT_OWNER, SRC_OWNER, SRC_DB, TRG_OWNER, TRG_DB, TRG_TABLE_NAME)
  USING INDEX COPYDATA_PROJECTS_PK
  ENABLE VALIDATE);